export const ACTION_TYPE = {
    FETCH_START:"FETCH_START",
    FETCH_SUCCESS:"FETCH_SUCCESS",
    FETCH_ERROR:"FETCH_ERROR",
    FORM_PROCESSING:"FORM_PROCESSING",
    SUBMIT_SUCCESS:"SUBMIT_SUCCESS",
    SUBMIT_FAILED:"SUBMIT_FAILED",
    EDIT_SUCCESS:"EDIT_SUCCESS",
    EDIT_FAILEED:"EDIT_FAILEED",
    DELTE_SUCCESS:"DELTE_SUCCESS",
    DELTE_FAILED:"DELTE_FAILED"
}